version: "3.9"

services:
  server:
    image: ${CALGPT_IMAGE_REPO}:${CALGPT_IMAGE_TAG}
    container_name: server
    restart: unless-stopped

    # השרת מאזין ב-8080 (CloudFront → EC2:8080)
    ports:
      - "8080:8080"

    # מפתחות ה-JWT נטענים מהנתיב /keys כפי שמוגדר ב-application.properties
    volumes:
      - /opt/calendargpt/keys:/keys:ro

    # משתני סביבה שהאפליקציה צריכה
    environment:
      SPRING_PROFILES_ACTIVE: prod
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      # אופציונלי: לכוונון JVM
      JAVA_OPTS: "-Xms256m -Xmx1024m"

    # תמיד למשוך אימג' חדש בהרצה
    pull_policy: always

    # Healthcheck בסיסי
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

    # לוגים עם רוטציה
    logging:
      options:
        max-size: "10m"
        max-file: "5"

    labels:
      # מאפשר עדכון אוטומטי אם תבחר להריץ Watchtower (לא חובה)
      com.centurylinklabs.watchtower.enable: "true"

# אופציונלי: עדכון אוטומטי של הקונטיינר כשיש אימג' חדש
#  watchtower:
#    image: containrrr/watchtower
#    container_name: watchtower
#    restart: unless-stopped
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 60 --label-enable
