version: "3.8"

services:
  appserver:
    container_name: server
    image: "${IMAGE_REPO:-barschtalman/calendergpt}:${APP_VERSION:-latest}"
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://node128.codingbc.com:7878/bars_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Nov2017890#
      JWT_PRIVATE_KEY_PATH: file:/keys/private_key.pem
      JWT_PUBLIC_KEY_PATH: file:/keys/public_key.pem
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - postgres
    volumes:
      - /opt/bars_project/keys:/keys:ro

  postgres:
    image: postgres:15
    container_name: postgres-calendar
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar_gpt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calendar_gpt"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
