name: Build & Push to Docker Hub

on:
  push:
    branches:
      - '**'

env:
  IMAGE_NAME: barschtalman/calendergpt

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Prepare JWT keys
        run: |
          mkdir -p keys
          printf '%s\n' "${{ secrets.JWT_PRIVATE_KEY_PEM }}" > keys/private_key.pem
          printf '%s\n' "${{ secrets.JWT_PUBLIC_KEY_PEM }}" > keys/public_key.pem
          chmod 600 keys/private_key.pem keys/public_key.pem

      - name: Sanity check
        run: |
          ls -l keys
          head -n 2 keys/public_key.pem || true

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
