name: Deploy to EC2

on:
  push:
    branches:
      - "**"   # תריץ רק על main, אפשר לשנות לסניף אחר

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          IMAGE_NAME=barschtalman/calendergpt
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          IMAGE_NAME=barschtalman/calendergpt
          IMAGE_TAG=${{ github.sha }}
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -euo pipefail
            set -x

            IMAGE_NAME="barschtalman/calendergpt"
            IMAGE_TAG="${{ github.sha }}"
            COMPOSE_DIR="${{ secrets.EC2_COMPOSE_DIR }}"

            echo "Deploying ${IMAGE_NAME}:${IMAGE_TAG} in ${COMPOSE_DIR}"

            cd "$COMPOSE_DIR"

            # בדיקה אם יש docker-compose או docker compose
            if command -v docker-compose >/dev/null 2>&1; then
              DC="docker-compose"
            else
              DC="docker compose"
            fi

            # עדכון ה-image ב-service
            sed -i "s|image:\s*${IMAGE_NAME}:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g" docker-compose.yml

            $DC pull appserver
            $DC up -d appserver

            docker image prune -af || true
